// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// one.cpp
int one();
extern "C" SEXP _cpp11One_one() {
  BEGIN_CPP11
    return cpp11::as_sexp(one());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp11One_one", (DL_FUNC) &_cpp11One_one, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp11One(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
