// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// convolve2cpp
Rcpp::NumericVector convolve2cpp(Rcpp::NumericVector a, Rcpp::NumericVector b);
RcppExport SEXP _convolve_convolve2cpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(convolve2cpp(a, b));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _convolve_convolve2(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_convolve_convolve2cpp", (DL_FUNC) &_convolve_convolve2cpp, 2},
    {"_convolve_convolve2", (DL_FUNC) &_convolve_convolve2, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_convolve(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
