# Generated by cpp11: do not edit by hand

print_df_by_col <- function(df, which_col) {
  invisible(.Call(`_cpp11DataTypes_print_df_by_col`, df, which_col))
}

print_df_by_row <- function(df, which_row) {
  invisible(.Call(`_cpp11DataTypes_print_df_by_row`, df, which_row))
}
