# Generated by cpp11: do not edit by hand

one <- function() {
  .Call(`_cppSimpleFuncs_one`)
}

ones <- function(n) {
  .Call(`_cppSimpleFuncs_ones`, n)
}

mean_cpp <- function(x) {
  .Call(`_cppSimpleFuncs_mean_cpp`, x)
}

any_cpp <- function(x) {
  .Call(`_cppSimpleFuncs_any_cpp`, x)
}

all_cpp <- function(x) {
  .Call(`_cppSimpleFuncs_all_cpp`, x)
}

greater_than <- function(x, y) {
  .Call(`_cppSimpleFuncs_greater_than`, x, y)
}

range_cpp <- function(x) {
  .Call(`_cppSimpleFuncs_range_cpp`, x)
}
