# Generated by cpp11: do not edit by hand

one <- function() {
  .Call(`_cpp11SimpleFuncs_one`)
}

ones <- function(n) {
  .Call(`_cpp11SimpleFuncs_ones`, n)
}

mean_cpp <- function(x) {
  .Call(`_cpp11SimpleFuncs_mean_cpp`, x)
}

any_cpp <- function(x) {
  .Call(`_cpp11SimpleFuncs_any_cpp`, x)
}

all_cpp <- function(x) {
  .Call(`_cpp11SimpleFuncs_all_cpp`, x)
}

greater_than <- function(x, y) {
  .Call(`_cpp11SimpleFuncs_greater_than`, x, y)
}

range_cpp <- function(x) {
  .Call(`_cpp11SimpleFuncs_range_cpp`, x)
}
